use crate::ir::*;
use crate::emitters::{Emitter, OutputFormat};

pub struct MasmEmitter;

impl Emitter for MasmEmitter {
    fn format(&self) -> OutputFormat {
        OutputFormat::Masm
    }

    fn emit(&self, program: &Program) -> String {
        let mut out = String::new();

        // === Header: processor + model directives ===
        emit_header(&mut out, program);

        // === Option directives ===
        out.push_str("option casemap:none\n\n");

        // === INCLUDE / INCLUDELIB from externs ===
        emit_includes(&mut out, program);

        // === EXTERNDEF declarations ===
        emit_externs(&mut out, program);

        // === Constant definitions (EQU) ===
        emit_constants(&mut out, program);

        // === Enum definitions (EQU series) ===
        emit_enums(&mut out, program);

        // === Struct definitions ===
        emit_structs(&mut out, program);

        // === Sections ===
        for section in &program.sections {
            emit_section(&mut out, section, program);
        }

        // === END directive ===
        emit_end(&mut out, program);

        out
    }
}

// ─── Header: processor model ────────────────────────────────────────────

fn emit_header(out: &mut String, program: &Program) {
    out.push_str("; Generated by ASM-BIB — MASM dialect\n");

    // Processor directive
    match program.arch {
        Arch::X86_16 => out.push_str(".8086\n"),
        Arch::X86_32 => out.push_str(".686p\n.mmx\n.xmm\n"),
        Arch::X86_64 => {
            // ML64 doesn't need .686 — it's implicit
        }
        _ => {}
    }

    // Memory model
    let fmt = program.format.to_lowercase();
    match program.arch {
        Arch::X86_16 => {
            if fmt.contains("com") {
                out.push_str(".model tiny\n");
            } else {
                out.push_str(".model small, c\n");
            }
        }
        Arch::X86_32 => {
            if fmt.contains("stdcall") || fmt.contains("win") || fmt.contains("pe") {
                out.push_str(".model flat, stdcall\n");
            } else {
                out.push_str(".model flat, c\n");
            }
        }
        Arch::X86_64 => {
            // ML64 doesn't use .model — flat 64 is implicit
        }
        _ => {}
    }

    out.push('\n');
}

// ─── INCLUDE / INCLUDELIB ───────────────────────────────────────────────

fn emit_includes(out: &mut String, program: &Program) {
    if program.externs.is_empty() {
        return;
    }

    // Collect unique library hints from extern names
    let mut libs: Vec<String> = Vec::new();

    for ext in &program.externs {
        // Heuristic: common Win32/64 API → includelib
        let name_lower = ext.name.to_lowercase();
        let lib = if name_lower.starts_with("printf") || name_lower.starts_with("malloc")
            || name_lower.starts_with("free") || name_lower.starts_with("exit")
        {
            "msvcrt.lib"
        } else if name_lower.starts_with("message") || name_lower.starts_with("create")
            || name_lower.starts_with("show") || name_lower.starts_with("dispatch")
            || name_lower.starts_with("def") || name_lower.starts_with("post")
            || name_lower.starts_with("get") || name_lower.starts_with("load")
            || name_lower.starts_with("send")
        {
            "user32.lib"
        } else if name_lower.starts_with("exitprocess") || name_lower.starts_with("getmodule")
            || name_lower.starts_with("getstd") || name_lower.starts_with("write")
            || name_lower.starts_with("read") || name_lower.starts_with("virtualalloc")
            || name_lower.starts_with("virtualfree") || name_lower.starts_with("heapalloc")
            || name_lower.starts_with("heapfree") || name_lower.starts_with("createfile")
            || name_lower.starts_with("closehandle")
        {
            "kernel32.lib"
        } else {
            ""
        };

        if !lib.is_empty() && !libs.contains(&lib.to_string()) {
            libs.push(lib.to_string());
        }
    }

    for lib in &libs {
        out.push_str(&format!("INCLUDELIB {}\n", lib));
    }

    if !libs.is_empty() {
        out.push('\n');
    }
}

// ─── EXTERNDEF ──────────────────────────────────────────────────────────

fn emit_externs(out: &mut String, program: &Program) {
    if program.externs.is_empty() {
        return;
    }

    for ext in &program.externs {
        if ext.is_function {
            out.push_str(&format!("EXTERNDEF {}:PROC\n", ext.name));
        } else {
            out.push_str(&format!("EXTERNDEF {}:BYTE\n", ext.name));
        }
    }
    out.push('\n');
}

// ─── Constants (EQU / =) ───────────────────────────────────────────────

fn emit_constants(out: &mut String, program: &Program) {
    if program.constants.is_empty() {
        return;
    }

    for c in &program.constants {
        if c.is_pub {
            out.push_str(&format!("PUBLIC {}\n", c.name));
        }
        out.push_str(&format!("{} EQU {}\n", c.name, c.value));
    }
    out.push('\n');
}

// ─── Enums → EQU series ────────────────────────────────────────────────

fn emit_enums(out: &mut String, program: &Program) {
    if program.enums.is_empty() {
        return;
    }

    for en in &program.enums {
        out.push_str(&format!("; enum {}\n", en.name));
        for (variant, value) in &en.variants {
            out.push_str(&format!("{}_{} EQU {}\n", en.name, variant, value));
        }
        out.push('\n');
    }
}

// ─── Structs → STRUCT / ENDS ───────────────────────────────────────────

fn emit_structs(out: &mut String, program: &Program) {
    if program.structs.is_empty() {
        return;
    }

    for s in &program.structs {
        if s.is_pub {
            out.push_str(&format!("PUBLIC {}\n", s.name));
        }
        out.push_str(&format!("{} STRUCT\n", s.name));
        for field in &s.fields {
            let type_name = size_to_masm_type(field.size);
            out.push_str(&format!("    {} {}  ?\n", field.name, type_name));
        }
        out.push_str(&format!("{} ENDS\n\n", s.name));
    }
}

fn size_to_masm_type(bytes: usize) -> &'static str {
    match bytes {
        1 => "BYTE",
        2 => "WORD",
        4 => "DWORD",
        8 => "QWORD",
        16 => "XMMWORD",
        32 => "YMMWORD",
        64 => "ZMMWORD",
        _ => "BYTE",
    }
}

// ─── Section emission ──────────────────────────────────────────────────

fn emit_section(out: &mut String, section: &Section, program: &Program) {
    // Section header
    match &section.kind {
        SectionKind::Text => out.push_str(".code\n"),
        SectionKind::Data => out.push_str(".data\n"),
        SectionKind::Bss => out.push_str(".data?\n"),
        SectionKind::Rodata => out.push_str(".const\n"),
        SectionKind::Custom(name) => out.push_str(&format!("{} SEGMENT\n", name)),
    }

    // Data items
    for item in &section.data {
        if item.is_pub {
            out.push_str(&format!("PUBLIC {}\n", item.name));
        }
        if let Some(align) = item.alignment {
            out.push_str(&format!("ALIGN {}\n", align));
        }
        emit_data_item(out, &item.name, &item.def);
    }

    // Functions
    for func in &section.functions {
        emit_function(out, func, program);
    }

    // Close custom segment
    if let SectionKind::Custom(name) = &section.kind {
        out.push_str(&format!("{} ENDS\n", name));
    }

    out.push('\n');
}

// ─── Function emission (PROC / ENDP) ───────────────────────────────────

fn emit_function(out: &mut String, func: &Function, _program: &Program) {
    // PUBLIC declaration
    if func.exported {
        out.push_str(&format!("PUBLIC {}\n", func.name));
    }

    // PROC header with params
    if func.params.is_empty() {
        out.push_str(&format!("{} PROC\n", func.name));
    } else {
        let params: Vec<String> = func.params.iter().map(|p| {
            let type_name = size_to_masm_type(p.size);
            format!("{}:{}", p.name, type_name)
        }).collect();
        out.push_str(&format!("{} PROC {}\n", func.name, params.join(", ")));
    }

    // LOCAL declarations
    if !func.local_vars.is_empty() {
        let locals: Vec<String> = func.local_vars.iter().map(|v| {
            let type_name = size_to_masm_type(v.size);
            format!("{}:{}", v.name, type_name)
        }).collect();
        out.push_str(&format!("    LOCAL {}\n", locals.join(", ")));
    }

    // Instruction body
    for item in &func.instructions {
        match item {
            FunctionItem::Label(lbl) => {
                out.push_str(&format!("{}:\n", lbl));
            }
            FunctionItem::Comment(text) => {
                out.push_str(&format!("    ; {}\n", text));
            }
            FunctionItem::Instruction(instr) => {
                out.push_str(&format!("    {}\n", emit_instruction(instr)));
            }
        }
    }

    // ENDP
    out.push_str(&format!("{} ENDP\n\n", func.name));
}

// ─── Instruction emission ──────────────────────────────────────────────

fn emit_instruction(instr: &Instruction) -> String {
    let mnemonic = masm_mnemonic(&instr.opcode);

    if instr.operands.is_empty() {
        return mnemonic.to_string();
    }

    // Determine if we need size qualifiers on memory operands
    let inferred_size = infer_operand_size(&instr.operands);

    let ops: Vec<String> = instr.operands.iter().map(|op| {
        emit_operand(op, inferred_size)
    }).collect();

    format!("{} {}", mnemonic, ops.join(", "))
}

/// Some opcodes have different names in MASM vs generic
fn masm_mnemonic(opcode: &Opcode) -> &str {
    match opcode {
        Opcode::RepMovsb => "rep movsb",
        Opcode::RepStosb => "rep stosb",
        _ => opcode.name(),
    }
}

// ─── Operand emission ──────────────────────────────────────────────────

fn emit_operand(op: &Operand, inferred_size: Option<Size>) -> String {
    match op {
        Operand::Reg(reg) => reg.name(),
        Operand::Imm(val) => {
            if *val < 0 {
                format!("-{}", -val)
            } else if *val > 9 {
                // MASM convention: hex with trailing 'h'
                let hex = format!("{:X}h", val);
                // If starts with letter, prefix with 0
                if hex.starts_with(|c: char| c.is_ascii_alphabetic()) {
                    format!("0{}", hex)
                } else {
                    hex
                }
            } else {
                val.to_string()
            }
        }
        Operand::Label(name) => name.clone(),
        Operand::StringLit(s) => format!("\"{}\"", s),
        Operand::Memory { base, index, scale, disp } => {
            emit_memory(base, index, *scale, *disp, inferred_size)
        }
    }
}

fn emit_memory(
    base: &Option<Register>,
    index: &Option<Register>,
    scale: u8,
    disp: i64,
    inferred_size: Option<Size>,
) -> String {
    let mut parts = Vec::new();

    if let Some(b) = base {
        parts.push(b.name());
    }

    if let Some(idx) = index {
        if scale > 1 {
            parts.push(format!("{}*{}", idx.name(), scale));
        } else {
            parts.push(idx.name());
        }
    }

    if disp != 0 || parts.is_empty() {
        if disp < 0 && !parts.is_empty() {
            let inner = parts.join(" + ");
            let addr = format!("[{} - {}]", inner, -disp);
            return maybe_size_prefix(addr, inferred_size);
        } else if disp > 9 {
            let hex = format!("{:X}h", disp);
            let hex = if hex.starts_with(|c: char| c.is_ascii_alphabetic()) {
                format!("0{}", hex)
            } else {
                hex
            };
            parts.push(hex);
        } else {
            parts.push(format!("{}", disp));
        }
    }

    let addr = format!("[{}]", parts.join(" + "));
    maybe_size_prefix(addr, inferred_size)
}

/// Add BYTE PTR / WORD PTR / DWORD PTR / QWORD PTR prefix for memory operands
fn maybe_size_prefix(addr: String, size: Option<Size>) -> String {
    match size {
        Some(Size::Byte) => format!("BYTE PTR {}", addr),
        Some(Size::Word) => format!("WORD PTR {}", addr),
        Some(Size::Dword) => format!("DWORD PTR {}", addr),
        Some(Size::Qword) => format!("QWORD PTR {}", addr),
        Some(Size::Xmmword) => format!("XMMWORD PTR {}", addr),
        Some(Size::Ymmword) => format!("YMMWORD PTR {}", addr),
        Some(Size::Zmmword) => format!("ZMMWORD PTR {}", addr),
        None => addr,
    }
}

/// Infer the operand size from register operands to qualify memory accesses
fn infer_operand_size(operands: &[Operand]) -> Option<Size> {
    for op in operands {
        if let Operand::Reg(reg) = op {
            return Some(reg.size());
        }
    }
    None
}

// ─── Data item emission ────────────────────────────────────────────────

fn emit_data_item(out: &mut String, name: &str, def: &DataDef) {
    match def {
        DataDef::Byte(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:02X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} BYTE {}\n", name, list.join(", ")));
        }
        DataDef::Word(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:04X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} WORD {}\n", name, list.join(", ")));
        }
        DataDef::Dword(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:08X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} DWORD {}\n", name, list.join(", ")));
        }
        DataDef::Qword(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:016X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} QWORD {}\n", name, list.join(", ")));
        }
        DataDef::String(s) => {
            let escaped = escape_masm_string(s);
            out.push_str(&format!("{} BYTE {}, 0\n", name, escaped));
        }
        DataDef::WString(s) => {
            let units: Vec<String> = s.encode_utf16().map(|u| {
                if u > 9 {
                    let h = format!("{:04X}h", u);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    u.to_string()
                }
            }).collect();
            out.push_str(&format!("{} WORD {}, 0\n", name, units.join(", ")));
        }
        DataDef::ReserveBytes(n) => {
            out.push_str(&format!("{} BYTE {} DUP(?)\n", name, n));
        }
        DataDef::ReserveWords(n) => {
            out.push_str(&format!("{} WORD {} DUP(?)\n", name, n));
        }
        DataDef::ReserveDwords(n) => {
            out.push_str(&format!("{} DWORD {} DUP(?)\n", name, n));
        }
        DataDef::ReserveQwords(n) => {
            out.push_str(&format!("{} QWORD {} DUP(?)\n", name, n));
        }
        DataDef::Float32(vals) => {
            let vs: Vec<String> = vals.iter().map(|v| format!("{}", v)).collect();
            out.push_str(&format!("{} REAL4 {}\n", name, vs.join(", ")));
        }
        DataDef::Float64(vals) => {
            let vs: Vec<String> = vals.iter().map(|v| format!("{}", v)).collect();
            out.push_str(&format!("{} REAL8 {}\n", name, vs.join(", ")));
        }
        DataDef::Struct(struct_name, fields) => {
            out.push_str(&format!("{} {} <", name, struct_name));
            let field_vals: Vec<String> = fields.iter().map(|f| {
                match &f.def {
                    DataDef::Byte(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Word(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Dword(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Qword(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::String(s) => format!("\"{}\"", s),
                    _ => "?".to_string(),
                }
            }).collect();
            out.push_str(&field_vals.join(", "));
            out.push_str(">\n");
        }
    }
}

/// Escape a string for MASM: split on control chars
fn escape_masm_string(s: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();

    for ch in s.chars() {
        match ch {
            '\n' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0Ah".to_string());
            }
            '\r' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0Dh".to_string());
            }
            '\t' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("09h".to_string());
            }
            '\0' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0".to_string());
            }
            _ => current.push(ch),
        }
    }

    if !current.is_empty() {
        parts.push(format!("\"{}\"", current));
    }

    if parts.is_empty() {
        "\"\"".to_string()
    } else {
        parts.join(", ")
    }
}

// ─── END directive ─────────────────────────────────────────────────────

fn emit_end(out: &mut String, program: &Program) {
    // Find entry point: first exported function named "main" or "_start" or "WinMain"
    let entry = program.sections.iter()
        .flat_map(|s| s.functions.iter())
        .find(|f| f.exported && (f.name == "main" || f.name == "_start"
            || f.name == "WinMain" || f.name == "wWinMain"
            || f.name == "mainCRTStartup" || f.name == "WinMainCRTStartup"))
        .map(|f| f.name.as_str());

    match entry {
        Some(name) => out.push_str(&format!("END {}\n", name)),
        None => out.push_str("END\n"),
    }
}
