use crate::ir::*;
use crate::emitters::{Emitter, OutputFormat};

pub struct MasmEmitter;

impl Emitter for MasmEmitter {
    fn format(&self) -> OutputFormat {
        OutputFormat::Masm
    }

    fn emit(&self, program: &Program) -> String {
        let mut out = String::new();

        // Collect all call targets to auto-declare externs
        let defined_funcs = collect_defined_functions(program);
        let call_targets = collect_call_targets(program);
        let auto_externs: Vec<String> = call_targets.into_iter()
            .filter(|name| !defined_funcs.contains(name))
            .collect();

        // === Header: processor + model directives ===
        emit_header(&mut out, program);

        // === Option directives ===
        out.push_str("option casemap:none\n\n");

        // === INCLUDELIB from auto-detected externs ===
        emit_includes_auto(&mut out, program, &auto_externs);

        // === EXTERNDEF declarations (explicit + auto) ===
        emit_externs_auto(&mut out, program, &auto_externs);

        // === Constant definitions (EQU) ===
        emit_constants(&mut out, program);

        // === Enum definitions (EQU series) ===
        emit_enums(&mut out, program);

        // === Struct definitions ===
        emit_structs(&mut out, program);

        // === Sections ===
        for section in &program.sections {
            emit_section(&mut out, section, program);
        }

        // === END directive ===
        emit_end(&mut out, program);

        out
    }
}

// ─── Header: processor model ────────────────────────────────────────────

fn emit_header(out: &mut String, program: &Program) {
    out.push_str("; Generated by ASM-BIB -- MASM dialect\n");

    // Processor directive
    match program.arch {
        Arch::X86_16 => out.push_str(".8086\n"),
        Arch::X86_32 => out.push_str(".686p\n.mmx\n.xmm\n"),
        Arch::X86_64 => {
            // ML64 doesn't need .686 — it's implicit
        }
        _ => {}
    }

    // Memory model
    let fmt = program.format.to_lowercase();
    match program.arch {
        Arch::X86_16 => {
            if fmt.contains("com") {
                out.push_str(".model tiny\n");
            } else {
                out.push_str(".model small, c\n");
            }
        }
        Arch::X86_32 => {
            if fmt.contains("stdcall") || fmt.contains("win") || fmt.contains("pe") {
                out.push_str(".model flat, stdcall\n");
            } else {
                out.push_str(".model flat, c\n");
            }
        }
        Arch::X86_64 => {
            // ML64 doesn't use .model — flat 64 is implicit
        }
        _ => {}
    }

    out.push('\n');
}

// ─── Collect call targets + defined functions ───────────────────────────

fn collect_defined_functions(program: &Program) -> Vec<String> {
    program.sections.iter()
        .flat_map(|s| s.functions.iter())
        .map(|f| f.name.clone())
        .collect()
}

fn collect_call_targets(program: &Program) -> Vec<String> {
    let mut targets = Vec::new();
    for sec in &program.sections {
        for func in &sec.functions {
            for item in &func.instructions {
                if let FunctionItem::Instruction(instr) = item {
                    if matches!(instr.opcode, Opcode::Call) {
                        for op in &instr.operands {
                            if let Operand::Label(name) = op {
                                if !targets.contains(name) {
                                    targets.push(name.clone());
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    targets
}

fn infer_lib(name: &str) -> &'static str {
    let n = name.to_lowercase();
    if n.starts_with("printf") || n.starts_with("scanf") || n.starts_with("malloc")
        || n.starts_with("free") || n.starts_with("calloc") || n.starts_with("realloc")
        || n.starts_with("puts") || n.starts_with("getchar") || n.starts_with("putchar")
        || n.starts_with("sprintf") || n.starts_with("fprintf") || n.starts_with("sscanf")
        || n.starts_with("atoi") || n.starts_with("atof") || n.starts_with("strlen")
        || n.starts_with("strcpy") || n.starts_with("strcat") || n.starts_with("strcmp")
        || n.starts_with("memcpy") || n.starts_with("memset") || n.starts_with("memmove")
        || n == "exit" || n == "_exit"
    {
        "msvcrt.lib"
    } else if n.starts_with("messagebox") || n.starts_with("createwindow")
        || n.starts_with("showwindow") || n.starts_with("dispatchmessage")
        || n.starts_with("defwindowproc") || n.starts_with("postquitmessage")
        || n.starts_with("getmessage") || n.starts_with("loadcursor")
        || n.starts_with("loadicon") || n.starts_with("sendmessage")
        || n.starts_with("registerclass") || n.starts_with("updatewindow")
        || n.starts_with("destroywindow")
    {
        "user32.lib"
    } else if n.starts_with("exitprocess") || n.starts_with("getmodulehandle")
        || n.starts_with("getstdhandle") || n.starts_with("writefile")
        || n.starts_with("readfile") || n.starts_with("writeconsole")
        || n.starts_with("readconsole") || n.starts_with("virtualalloc")
        || n.starts_with("virtualfree") || n.starts_with("heapalloc")
        || n.starts_with("heapfree") || n.starts_with("createfile")
        || n.starts_with("closehandle") || n.starts_with("getprocessheap")
        || n.starts_with("getlasterror") || n.starts_with("setlasterror")
        || n.starts_with("getcommandline") || n.starts_with("sleep")
        || n.starts_with("createthread") || n.starts_with("getprocaddress")
        || n.starts_with("loadlibrary") || n.starts_with("freelibrary")
    {
        "kernel32.lib"
    } else {
        ""
    }
}

// ─── INCLUDELIB (auto-detected from call targets) ───────────────────────

fn emit_includes_auto(out: &mut String, program: &Program, auto_externs: &[String]) {
    let mut libs: Vec<&str> = Vec::new();

    // From explicit externs
    for ext in &program.externs {
        let lib = infer_lib(&ext.name);
        if !lib.is_empty() && !libs.contains(&lib) {
            libs.push(lib);
        }
    }

    // From auto-detected call targets
    for name in auto_externs {
        let lib = infer_lib(name);
        if !lib.is_empty() && !libs.contains(&lib) {
            libs.push(lib);
        }
    }

    for lib in &libs {
        out.push_str(&format!("INCLUDELIB {}\n", lib));
    }
    if !libs.is_empty() {
        out.push('\n');
    }
}

// ─── EXTERNDEF (explicit + auto-detected) ───────────────────────────────

fn emit_externs_auto(out: &mut String, program: &Program, auto_externs: &[String]) {
    let mut emitted: Vec<String> = Vec::new();

    // Explicit externs from IR
    for ext in &program.externs {
        if ext.is_function {
            out.push_str(&format!("EXTERNDEF {}:PROC\n", ext.name));
        } else {
            out.push_str(&format!("EXTERNDEF {}:BYTE\n", ext.name));
        }
        emitted.push(ext.name.clone());
    }

    // Auto-detected externs (call targets not defined locally)
    for name in auto_externs {
        if !emitted.contains(name) {
            out.push_str(&format!("EXTERNDEF {}:PROC\n", name));
            emitted.push(name.clone());
        }
    }

    if !emitted.is_empty() {
        out.push('\n');
    }
}

// ─── Constants (EQU / =) ───────────────────────────────────────────────

fn emit_constants(out: &mut String, program: &Program) {
    if program.constants.is_empty() {
        return;
    }

    for c in &program.constants {
        if c.is_pub {
            out.push_str(&format!("PUBLIC {}\n", c.name));
        }
        out.push_str(&format!("{} EQU {}\n", c.name, c.value));
    }
    out.push('\n');
}

// ─── Enums → EQU series ────────────────────────────────────────────────

fn emit_enums(out: &mut String, program: &Program) {
    if program.enums.is_empty() {
        return;
    }

    for en in &program.enums {
        out.push_str(&format!("; enum {}\n", en.name));
        for (variant, value) in &en.variants {
            out.push_str(&format!("{}_{} EQU {}\n", en.name, variant, value));
        }
        out.push('\n');
    }
}

// ─── Structs → STRUCT / ENDS ───────────────────────────────────────────

fn emit_structs(out: &mut String, program: &Program) {
    if program.structs.is_empty() {
        return;
    }

    for s in &program.structs {
        if s.is_pub {
            out.push_str(&format!("PUBLIC {}\n", s.name));
        }
        out.push_str(&format!("{} STRUCT\n", s.name));
        for field in &s.fields {
            let type_name = size_to_masm_type(field.size);
            out.push_str(&format!("    {} {}  ?\n", field.name, type_name));
        }
        out.push_str(&format!("{} ENDS\n\n", s.name));
    }
}

fn size_to_masm_type(bytes: usize) -> &'static str {
    match bytes {
        1 => "BYTE",
        2 => "WORD",
        4 => "DWORD",
        8 => "QWORD",
        16 => "XMMWORD",
        32 => "YMMWORD",
        64 => "ZMMWORD",
        _ => "BYTE",
    }
}

// ─── Section emission ──────────────────────────────────────────────────

fn emit_section(out: &mut String, section: &Section, program: &Program) {
    // Section header
    match &section.kind {
        SectionKind::Text => out.push_str(".code\n"),
        SectionKind::Data => out.push_str(".data\n"),
        SectionKind::Bss => out.push_str(".data?\n"),
        SectionKind::Rodata => out.push_str(".const\n"),
        SectionKind::Custom(name) => out.push_str(&format!("{} SEGMENT\n", name)),
    }

    // Data items
    for item in &section.data {
        if item.is_pub {
            out.push_str(&format!("PUBLIC {}\n", item.name));
        }
        if let Some(align) = item.alignment {
            out.push_str(&format!("ALIGN {}\n", align));
        }
        emit_data_item(out, &item.name, &item.def);
    }

    // Functions
    for func in &section.functions {
        emit_function(out, func, program);
    }

    // Close custom segment
    if let SectionKind::Custom(name) = &section.kind {
        out.push_str(&format!("{} ENDS\n", name));
    }

    out.push('\n');
}

// ─── Function emission (PROC / ENDP) ───────────────────────────────────

fn emit_function(out: &mut String, func: &Function, _program: &Program) {
    // PUBLIC declaration
    if func.exported {
        out.push_str(&format!("PUBLIC {}\n", func.name));
    }

    // PROC header with params
    if func.params.is_empty() {
        out.push_str(&format!("{} PROC\n", func.name));
    } else {
        let params: Vec<String> = func.params.iter().map(|p| {
            let type_name = size_to_masm_type(p.size);
            format!("{}:{}", p.name, type_name)
        }).collect();
        out.push_str(&format!("{} PROC {}\n", func.name, params.join(", ")));
    }

    // LOCAL declarations
    if !func.local_vars.is_empty() {
        let locals: Vec<String> = func.local_vars.iter().map(|v| {
            let type_name = size_to_masm_type(v.size);
            format!("{}:{}", v.name, type_name)
        }).collect();
        out.push_str(&format!("    LOCAL {}\n", locals.join(", ")));
    }

    // Instruction body
    for item in &func.instructions {
        match item {
            FunctionItem::Label(lbl) => {
                out.push_str(&format!("{}:\n", lbl));
            }
            FunctionItem::Comment(text) => {
                out.push_str(&format!("    ; {}\n", text));
            }
            FunctionItem::Instruction(instr) => {
                out.push_str(&format!("    {}\n", emit_instruction(instr)));
            }
        }
    }

    // ENDP
    out.push_str(&format!("{} ENDP\n\n", func.name));
}

// ─── Instruction emission ──────────────────────────────────────────────

fn emit_instruction(instr: &Instruction) -> String {
    let mnemonic = masm_mnemonic(&instr.opcode);

    if instr.operands.is_empty() {
        return mnemonic.to_string();
    }

    // Determine if we need size qualifiers on memory operands
    let inferred_size = infer_operand_size(&instr.operands);

    // Detect which operands are memory-context (Label used as data ref, not branch target)
    let is_branch = matches!(instr.opcode,
        Opcode::Jmp | Opcode::Je | Opcode::Jne | Opcode::Jl | Opcode::Jle |
        Opcode::Jg | Opcode::Jge | Opcode::Jb | Opcode::Jbe | Opcode::Ja | Opcode::Jae |
        Opcode::Call | Opcode::B | Opcode::Bl | Opcode::Beq | Opcode::Bne |
        Opcode::Blt | Opcode::Bgt | Opcode::Ble | Opcode::Bge |
        Opcode::Jal | Opcode::Jalr
    );

    let is_lea = matches!(instr.opcode, Opcode::Lea);

    let ops: Vec<String> = instr.operands.iter().map(|op| {
        let is_mem_ctx = matches!(op, Operand::Label(_)) && !is_branch && !is_lea;
        emit_operand(op, inferred_size, is_mem_ctx)
    }).collect();

    format!("{} {}", mnemonic, ops.join(", "))
}

/// Some opcodes have different names in MASM vs generic
fn masm_mnemonic(opcode: &Opcode) -> &str {
    match opcode {
        Opcode::RepMovsb => "rep movsb",
        Opcode::RepStosb => "rep stosb",
        _ => opcode.name(),
    }
}

// ─── Operand emission ──────────────────────────────────────────────────

fn emit_operand(op: &Operand, inferred_size: Option<Size>, is_memory_context: bool) -> String {
    match op {
        Operand::Reg(reg) => reg.name(),
        Operand::Imm(val) => emit_immediate(*val),
        Operand::Label(name) => {
            if is_memory_context {
                // Data label used as memory operand: add size qualifier
                maybe_size_prefix(name.clone(), inferred_size)
            } else {
                name.clone()
            }
        }
        Operand::StringLit(s) => format!("\"{}\"", s),
        Operand::Memory { base, index, scale, disp } => {
            emit_memory(base, index, *scale, *disp, inferred_size)
        }
    }
}

fn emit_immediate(val: i64) -> String {
    if val < 0 {
        format!("-{}", -val)
    } else if val > 9 {
        let hex = format!("{:X}h", val);
        if hex.starts_with(|c: char| c.is_ascii_alphabetic()) {
            format!("0{}", hex)
        } else {
            hex
        }
    } else {
        val.to_string()
    }
}

fn emit_memory(
    base: &Option<Register>,
    index: &Option<Register>,
    scale: u8,
    disp: i64,
    inferred_size: Option<Size>,
) -> String {
    let mut parts = Vec::new();

    if let Some(b) = base {
        parts.push(b.name());
    }

    if let Some(idx) = index {
        if scale > 1 {
            parts.push(format!("{}*{}", idx.name(), scale));
        } else {
            parts.push(idx.name());
        }
    }

    if disp != 0 || parts.is_empty() {
        if disp < 0 && !parts.is_empty() {
            let inner = parts.join(" + ");
            let addr = format!("[{} - {}]", inner, -disp);
            return maybe_size_prefix(addr, inferred_size);
        } else if disp > 9 {
            let hex = format!("{:X}h", disp);
            let hex = if hex.starts_with(|c: char| c.is_ascii_alphabetic()) {
                format!("0{}", hex)
            } else {
                hex
            };
            parts.push(hex);
        } else {
            parts.push(format!("{}", disp));
        }
    }

    let addr = format!("[{}]", parts.join(" + "));
    maybe_size_prefix(addr, inferred_size)
}

/// Add BYTE PTR / WORD PTR / DWORD PTR / QWORD PTR prefix for memory operands
fn maybe_size_prefix(addr: String, size: Option<Size>) -> String {
    match size {
        Some(Size::Byte) => format!("BYTE PTR {}", addr),
        Some(Size::Word) => format!("WORD PTR {}", addr),
        Some(Size::Dword) => format!("DWORD PTR {}", addr),
        Some(Size::Qword) => format!("QWORD PTR {}", addr),
        Some(Size::Xmmword) => format!("XMMWORD PTR {}", addr),
        Some(Size::Ymmword) => format!("YMMWORD PTR {}", addr),
        Some(Size::Zmmword) => format!("ZMMWORD PTR {}", addr),
        None => addr,
    }
}

/// Infer the operand size from register operands to qualify memory accesses
fn infer_operand_size(operands: &[Operand]) -> Option<Size> {
    for op in operands {
        if let Operand::Reg(reg) = op {
            return Some(reg.size());
        }
    }
    None
}

// ─── Data item emission ────────────────────────────────────────────────

fn emit_data_item(out: &mut String, name: &str, def: &DataDef) {
    match def {
        DataDef::Byte(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:02X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} BYTE {}\n", name, list.join(", ")));
        }
        DataDef::Word(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:04X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} WORD {}\n", name, list.join(", ")));
        }
        DataDef::Dword(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:08X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} DWORD {}\n", name, list.join(", ")));
        }
        DataDef::Qword(vals) => {
            let list: Vec<String> = vals.iter().map(|v| {
                if *v > 9 {
                    let h = format!("{:016X}h", v);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    v.to_string()
                }
            }).collect();
            out.push_str(&format!("{} QWORD {}\n", name, list.join(", ")));
        }
        DataDef::String(s) => {
            let escaped = escape_masm_string(s);
            out.push_str(&format!("{} BYTE {}, 0\n", name, escaped));
        }
        DataDef::WString(s) => {
            let units: Vec<String> = s.encode_utf16().map(|u| {
                if u > 9 {
                    let h = format!("{:04X}h", u);
                    if h.starts_with(|c: char| c.is_ascii_alphabetic()) { format!("0{}", h) } else { h }
                } else {
                    u.to_string()
                }
            }).collect();
            out.push_str(&format!("{} WORD {}, 0\n", name, units.join(", ")));
        }
        DataDef::ReserveBytes(n) => {
            out.push_str(&format!("{} BYTE {} DUP(?)\n", name, n));
        }
        DataDef::ReserveWords(n) => {
            out.push_str(&format!("{} WORD {} DUP(?)\n", name, n));
        }
        DataDef::ReserveDwords(n) => {
            out.push_str(&format!("{} DWORD {} DUP(?)\n", name, n));
        }
        DataDef::ReserveQwords(n) => {
            out.push_str(&format!("{} QWORD {} DUP(?)\n", name, n));
        }
        DataDef::Float32(vals) => {
            let vs: Vec<String> = vals.iter().map(|v| format!("{}", v)).collect();
            out.push_str(&format!("{} REAL4 {}\n", name, vs.join(", ")));
        }
        DataDef::Float64(vals) => {
            let vs: Vec<String> = vals.iter().map(|v| format!("{}", v)).collect();
            out.push_str(&format!("{} REAL8 {}\n", name, vs.join(", ")));
        }
        DataDef::Struct(struct_name, fields) => {
            out.push_str(&format!("{} {} <", name, struct_name));
            let field_vals: Vec<String> = fields.iter().map(|f| {
                match &f.def {
                    DataDef::Byte(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Word(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Dword(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::Qword(v) => v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                    DataDef::String(s) => format!("\"{}\"", s),
                    _ => "?".to_string(),
                }
            }).collect();
            out.push_str(&field_vals.join(", "));
            out.push_str(">\n");
        }
    }
}

/// Escape a string for MASM: split on control chars
fn escape_masm_string(s: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();

    for ch in s.chars() {
        match ch {
            '\n' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0Ah".to_string());
            }
            '\r' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0Dh".to_string());
            }
            '\t' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("09h".to_string());
            }
            '\0' => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push("0".to_string());
            }
            _ => current.push(ch),
        }
    }

    if !current.is_empty() {
        parts.push(format!("\"{}\"", current));
    }

    if parts.is_empty() {
        "\"\"".to_string()
    } else {
        parts.join(", ")
    }
}

// ─── END directive ─────────────────────────────────────────────────────

fn emit_end(out: &mut String, program: &Program) {
    // ML64 (x86_64): only `END` — no entry point argument
    // ML (x86_32/x86_16): `END main` with entry point
    match program.arch {
        Arch::X86_64 => {
            out.push_str("END\n");
        }
        Arch::X86_32 | Arch::X86_16 => {
            let entry = program.sections.iter()
                .flat_map(|s| s.functions.iter())
                .find(|f| f.exported && (f.name == "main" || f.name == "_start"
                    || f.name == "WinMain" || f.name == "wWinMain"
                    || f.name == "mainCRTStartup" || f.name == "WinMainCRTStartup"))
                .map(|f| f.name.as_str());

            match entry {
                Some(name) => out.push_str(&format!("END {}\n", name)),
                None => out.push_str("END\n"),
            }
        }
        _ => {
            out.push_str("END\n");
        }
    }
}
