; Generated by ASM-BIB — MASM dialect

option casemap:none

.data
result QWORD 0

.code
PUBLIC main
main PROC
    mov rax, 64h
    add rax, 0C8h
    mov rbx, 1F4h
    sub rbx, 96h
    imul rax, 4
    xor ecx, ecx
    call ExitProcess
main ENDP


END main
