; Generated by ASM-BIB — MASM dialect

option casemap:none

.code
PUBLIC main
main PROC
    mov rax, 0Ah
    cmp rax, 0Ah
    je equal
    jmp done
equal:
    mov rbx, 1
done:
    xor ecx, ecx
    call ExitProcess
main ENDP


END main
