; Generated by ASM-BIB -- MASM dialect

option casemap:none

INCLUDELIB kernel32.lib

EXTERNDEF ExitProcess:PROC

.data
pi REAL8 3.14
vals REAL4 1, 2

.code
PUBLIC main
main PROC
    movaps xmm0, XMMWORD PTR pi
    xor ecx, ecx
    call ExitProcess
main ENDP


END
