; Generated by ASM-BIB — MASM dialect

option casemap:none

.data
msg BYTE "Hello!", 0Ah, 0

.code
PUBLIC main
main PROC
    lea rcx, msg
    call printf
    xor ecx, ecx
    call ExitProcess
main ENDP


END main
