; Generated by ASM-BIB -- MASM dialect

option casemap:none

INCLUDELIB msvcrt.lib
INCLUDELIB kernel32.lib

EXTERNDEF printf:PROC
EXTERNDEF ExitProcess:PROC

.data
msg BYTE "Hello!", 0Ah, 0

.code
PUBLIC main
main PROC
    lea rcx, msg
    call printf
    xor ecx, ecx
    call ExitProcess
main ENDP


END
