; Generated by ASM-BIB — MASM dialect

option casemap:none

.data
value QWORD 000000000000002Ah
buffer BYTE 256 DUP(?)

.code
PUBLIC main
main PROC
    mov rax, QWORD PTR value
    mov QWORD PTR value, rbx
    lea rdi, buffer
    xor ecx, ecx
    call ExitProcess
main ENDP


END main
