; Generated by ASM-BIB — MASM dialect

option casemap:none

.data
src BYTE "Test", 0
dst BYTE 16 DUP(?)

.code
PUBLIC main
main PROC
    lea rsi, src
    lea rdi, dst
    mov rcx, 5
    rep movsb
    xor ecx, ecx
    call ExitProcess
main ENDP


END main
