; Generated by ASM-BIB -- MASM dialect
.686p
.mmx
.xmm
.model flat, stdcall

option casemap:none

INCLUDELIB kernel32.lib

EXTERNDEF ExitProcess:PROC

.data
msg BYTE "Hello 32-bit!", 0

.code
PUBLIC main
main PROC
    push 0
    lea eax, msg
    push eax
    push 0
    call ExitProcess
main ENDP


END main
