; Generated by ASM-BIB
bits 64

extern printf
extern scanf
extern ExitProcess

global DoMath
global DoSqrt
global main

section .data
    menu_str: db "1. Math test (pow)", 10, "2. Math test (sqrt)", 10, "3. Struct test", 10, "Select: ", 0
    fmt_int: db "%d", 0
    result_str: db "Result: %d", 10, 0
    float_res: db "Result: %f", 10, 0
    invalid_str: db "Invalid option!", 10, 0
    ; pts (struct Point3D)
field0: dd 1
field1: dd 2
field2: dd 3

section .bss
    choice: resd 1

section .text
DoMath:
    push rbp
    mov rbp, rsp
    sub rsp, 0x20
    mov rbx, 2
    mov rcx, 0xA
    mov rax, 1
    test rcx, rcx
    je __powdone_1
.__pow_0:
    imul rax, rbx
    dec rcx
    jne __pow_0
.__powdone_1:
    sub rsp, 0x28
    lea rcx, result_str
    mov rdx, rax
    call printf
    add rsp, 0x28
    leave
    ret

DoSqrt:
    push rbp
    mov rbp, rsp
    sub rsp, 0x20
    mov rax, 9
    cvtsi2ss xmm0, rax
    sqrtss xmm0, xmm0
    cvtss2si rax, xmm0
    sub rsp, 0x28
    lea rcx, result_str
    mov rdx, rax
    call printf
    add rsp, 0x28
    leave
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 0x28
    sub rsp, 0x28
    lea rcx, menu_str
    call printf
    add rsp, 0x28
    sub rsp, 0x28
    lea rcx, fmt_int
    lea rdx, choice
    call scanf
    add rsp, 0x28
    mov eax, [choice]
    cmp eax, 1
    jne __case_next_3
    call DoMath
    jmp __sw_end_2
.__case_next_3:
    cmp eax, 2
    jne __case_next_4
    call DoSqrt
    jmp __sw_end_2
.__case_next_4:
    cmp eax, 3
    jne __case_next_5
    lea rcx, pts
    movss xmm0, [rcx]
    addss xmm0, [rcx + 4]
    cvtss2si rax, xmm0
    sub rsp, 0x28
    lea rcx, result_str
    mov rdx, rax
    call printf
    add rsp, 0x28
    jmp __sw_end_2
.__case_next_5:
    sub rsp, 0x28
    lea rcx, invalid_str
    call printf
    add rsp, 0x28
    jmp __sw_end_2
.__sw_end_2:
    xor ecx, ecx
    call ExitProcess

