; Generated by ASM-BIB
bits 64

extern ExitProcess

global main

section .text
main:
    push rbp
    mov rbp, rsp
    sub rsp, 0x28
    mov r10, 0x1000
    mov r11, 0x2000
    call [r11 + 0x20]
    xor ecx, ecx
    call ExitProcess

