; Generated by ASM-BIB -- MASM dialect

option casemap:none

INCLUDELIB msvcrt.lib
INCLUDELIB kernel32.lib

EXTERNDEF printf:PROC
EXTERNDEF ExitProcess:PROC

.data
__str_0 BYTE "Hello, World!", 0Ah, 0

.code
PUBLIC main
main PROC
    sub rsp, 28h
    lea rcx, __str_0
    call printf
    add rsp, 28h
    xor ecx, ecx
    call ExitProcess
main ENDP


END
