; Generated by ASM-BIB
bits 64

extern MessageBoxA
extern ExitProcess

global main

section .data
    msg_title: db "ASM-BIB Test", 0
    msg_text: db "Fase 7+8 OK! COFF Production Quality.", 0

section .text
main:
    push rbp
    mov rbp, rsp
    sub rsp, 0x30
    xor ecx, ecx
    lea rdx, msg_text
    lea r8, msg_title
    xor r9d, r9d
    call MessageBoxA
    xor ecx, ecx
    call ExitProcess

